#!/bin/bash

# set up variables
fname="$(date +"%FT%H%M%z").html"

# do the conversion
markdown article.md > content.html
h1=$(hxextract h1 content.html | sed -e 's/<h1>//g' -e 's/<\/h1>//g')
echo $h1 > headline.html

sed -i 's/"$h1"//g' content.html

hxincl -f -x template.html > $fname

hxmultitoc > index.html

# clean up
rm headline.html
rm content.html

# Unused code for reference
# markdown --html4tags article.md | recode utf-8..cp1252 > content.html
