#!/bin/bash

# set up variables
fname="$(date +"%FT%H%M%z").html"

# do the conversion
markdown article.md > content.html
hxextract h1 content.html > headline.html
hxincl -f -x template.html > $fname

hxmultitoc > index.html

# clean up
rm headline.html
rm content.html

# Unused code for reference
# markdown --html4tags article.md | recode utf-8..cp1252 > content.html
