#!/bin/bash

# set up variables
fname="$(date +"%FT%H%M%z").html"

# do the conversion
markdown article.md > content.html
xmllint --html --xpath "//h1/text()" content.html > headline.html
hxincl -f -x template.html > $fname

hxmultitoc -s "<html><head><title>Index</title></head><body>" -e "</body></html>" *.html > index.html

# clean up
rm headline.html
rm content.html

# Unused code for reference
# markdown --html4tags article.md | recode utf-8..cp1252 > content.html
# h1=$(hxextract h1 content.html | sed -e 's/<h1>//g' -e 's/<\/h1>//g')
# sed -i 's/"$h1"//g' content.html
# xmllint --html --format $fname
# hxmultitoc > index.html
